/*:
  ros__parameters:
    use_sim_time: True

# PARAMETERS FOR RHODON ROBOT
$(var namespace):
  #-------------------------------------------------
  # HW DRIVERS
  #-------------------------------------------------
  ros2aria:
    ros__parameters:
      port: "/dev/sensors/patrolbot"
      serial_baud: 115200
      odom_frame: "$(var namespace)_odom"
      base_link_frame: "$(var namespace)_base_link"


  hokuyo_front:
    ros__parameters:
      angle_max: 1.4
      angle_min: -1.4
      ip_port: 1853723
      #serial_port: '/dev/sensors/hokuyo_urg'
      serial_port: '/dev/ttyACM0'
      serial_baud: 115200
      laser_frame_id: '$(var namespace)_laser_front_link'
      laser_topic_name: 'scan_front'
      calibrate_time: False
      default_user_latency: -0.2
      diagnostics_tolerance: 0.05
      diagnostics_window_time: 5.0
      error_limit: 4
      get_detailed_status: False
      publish_intensity: False
      publish_multiecho: False
      cluster: 1
      skip: 0

  hokuyo_back:
    ros__parameters:
      angle_max: 1.4
      angle_min: -1.4
      ip_port: 1853723
      #serial_port: '/dev/sensors/hokuyo_urg'
      serial_port: '/dev/ttyACM1'
      serial_baud: 115200
      laser_frame_id: '$(var namespace)_laser_back_link'
      laser_topic_name: 'scan_back'
      calibrate_time: False
      default_user_latency: -0.2
      diagnostics_tolerance: 0.05
      diagnostics_window_time: 5.0
      error_limit: 4
      get_detailed_status: False
      publish_intensity: False
      publish_multiecho: False
      cluster: 1
      skip: 0

  keyboard_control:
    ros__parameters:
      linear_v_inc: 0.1
      angular_v_inc: 0.3
      publish_topic: 'cmd_vel'

  #-------------------------------------------------
  # UTILS
  #-------------------------------------------------
  mqtt_bridge:
    ros__parameters:
      host: "150.214.109.137"       # MQTT broker ip
      port: 8002                    # MQTT broker TCP port
      username: ""
      password: ""
      MQTT_namespace: "rhodon"        # main topic
      MQTT_topics_subscribe: "tasks,NavToPose,/giraff/status,/reactive"  # subtopics to listen
      append_timestamp: false

  patrol_times:
    ros__parameters:
      # Add as many poses in the patrol as desired (starts in pose_1)
      pose_1: [0.0,0.0,0.0,0.0,0.0,0.0,1.0]   # lab 2.3.7
      pose_2: [0.0,5.0,0.0,0.0,0.0,0.0,1.0]   # lab 2.3.6
      pose_3: [4.6,-2.3,0.0,0.0,0.0,0.0,1.0]  # corridor

  battery_manager:
    ros__parameters:
      # main params
      verbose: False
      input_battery_topic: "battery"
      output_battery_topic: "battery_filtered"
      filter_lenght_samples: 30
      publish_rate: 2.0
      low_battery_voltage: 24.2
      critial_battery_voltage: 24.0

      # Log params
      create_log: False
      log_directory_path: "~"
      log_interval_sec: 20

  status_publisher:
    ros__parameters:
      output_topic: "/ros2mqtt"
      statusRate: 10.0
      map_frame: "map"
      base_frame: "$(var namespace)_base_link"
      battery_topic: "battery_filtered"

  ptu_tracking:
    ros__parameters:
      tag_frame_id: tag36h11:0
      camera_frame_id: camera
      ptu_frame_id: wxxms/base_link
      ptu_state_topic: /ptu/state
      loopRate: 5.0
  apriltag:
    ros__parameters:
      image_transport: raw    # image format
      family: 36h11           # tag family name
      size: 0.261             # tag edge size in meter
      max_hamming: 0          # maximum allowed hamming distance (corrected bits)

      # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
      detector:
        threads: 1          # number of threads
        decimate: 2.0       # decimate resolution for quad detection
        blur: 0.0           # sigma of Gaussian blur for quad detection
        refine: True        # snap to strong gradients
        sharpening: 0.25    # sharpening of decoded images
        debug: False        # write additional debugging images to current working directory

      # optional list of tags
      #tag:
      #  ids: [12]            # tag ID
      #  frames: [tag_link]  # optional frame name
      #  sizes: [0.173]   # optional tag-specific edge size
         
  slam_toolbox:
    ros__parameters:

      # Plugin params
      solver_plugin: solver_plugins::CeresSolver
      ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
      ceres_preconditioner: SCHUR_JACOBI
      ceres_trust_strategy: LEVENBERG_MARQUARDT
      ceres_dogleg_type: TRADITIONAL_DOGLEG
      ceres_loss_function: None

      # ROS Parameters
      odom_frame: $(var namespace)_odom
      map_frame: map
      base_frame: $(var namespace)_base_link
      scan_topic: scan_back
      mode: mapping #localization

      # if you'd like to immediately start continuing a map at a given pose
      # or at the dock, but they are mutually exclusive, if pose is given
      # will use pose
      #map_file_name: test_steve
      # map_start_pose: [0.0, 0.0, 0.0]
      #map_start_at_dock: true

      debug_logging: false
      throttle_scans: 1
      transform_publish_period: 0.02 #if 0 never publishes odometry
      map_update_interval: 5.0
      resolution: 0.05
      max_laser_range: 20.0 #for rastering images
      minimum_time_interval: 0.5
      transform_timeout: 0.2
      tf_buffer_duration: 30.
      stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
      enable_interactive_mode: true

      # General Parameters
      use_scan_matching: true
      use_scan_barycenter: true
      minimum_travel_distance: 0.5
      minimum_travel_heading: 0.5
      scan_buffer_size: 10
      scan_buffer_maximum_scan_distance: 10.0
      link_match_minimum_response_fine: 0.1  
      link_scan_maximum_distance: 1.5
      loop_search_maximum_distance: 3.0
      do_loop_closing: true 
      loop_match_minimum_chain_size: 10           
      loop_match_maximum_variance_coarse: 3.0  
      loop_match_minimum_response_coarse: 0.35    
      loop_match_minimum_response_fine: 0.45

      # Correlation Parameters - Correlation Parameters
      correlation_search_space_dimension: 0.5
      correlation_search_space_resolution: 0.01
      correlation_search_space_smear_deviation: 0.1 

      # Correlation Parameters - Loop Closure Parameters
      loop_search_space_dimension: 8.0
      loop_search_space_resolution: 0.05
      loop_search_space_smear_deviation: 0.03

      # Scan Matcher Parameters
      distance_variance_penalty: 0.5      
      angle_variance_penalty: 1.0    

      fine_search_angle_offset: 0.00349     
      coarse_search_angle_offset: 0.349   
      coarse_angle_resolution: 0.0349        
      minimum_angle_penalty: 0.9
      minimum_distance_penalty: 0.5
      use_response_expansion: true
