$(var namespace):
  #-------------------------------------------------
  # HW DRIVERS
  #-------------------------------------------------
  usb_cam:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      image_width: 640
      image_height: 480
      camera_name: "laptop_camera"
      #camera_info_url: "package://usb_cam/config/camera_info.yaml"
      camera_info_url: "file:///home/jgmonroy/.ros/camera_info/laptop_camera.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
  
  apriltag:
    ros__parameters:
      image_transport: raw    # image format
      family: 36h11           # tag family name
      size: 0.261             # tag edge size in meter
      max_hamming: 0          # maximum allowed hamming distance (corrected bits)

      # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
      detector:
        threads: 1          # number of threads
        decimate: 2.0       # decimate resolution for quad detection
        blur: 0.0           # sigma of Gaussian blur for quad detection
        refine: True        # snap to strong gradients
        sharpening: 0.25    # sharpening of decoded images
        debug: False        # write additional debugging images to current working directory

      # optional list of tags
      #tag:
      #  ids: [12]            # tag ID
      #  frames: [tag_link]  # optional frame name
      #  sizes: [0.173]   # optional tag-specific edge size
  
  hal_flir_d46:
    ros__parameters:
      port: /dev/ttyUSB0
      limits_enabled: True
      baud: 9600
      default_velocity: 0.1
      hz: 10  

      publishers:
        state: /ptu/state

      services:
        set_pan: /ptu/set_pan
        set_tilt: /ptu/set_tilt
        set_pantilt: /ptu/set_pan_tilt
        set_pantilt_speed: /ptu/set_pan_tilt_speed
        reset: /ptu/reset
        get_limits: /ptu/get_limits

      actions: 
        set_pan: /ptu/set_pan
        set_tilt: /ptu/set_tilt
        set_pantilt: /ptu/set_pan_tilt

      min_thresold_command_input_pan: 0.01
      min_thresold_command_input_tilt: 0.01
  

  ptu_tracking:
    ros__parameters:
      tag_frame_id: tag36h11:0
      camera_frame_id: camera
      ptu_frame_id: wxxms/base_link
      ptu_state_topic: /ptu/state
      loopRate: 5.0