#/*:
#  ros__parameters:
#    use_sim_time: True

$(var namespace):
  #-------------------------------------------------
  # HW DRIVERS
  #-------------------------------------------------
  usb_cam_0:
    usb_cam:
      ros__parameters:
        video_device: "/dev/video0"
        framerate: 5.0
        io_method: "mmap"
        frame_id: "usb_cam_0"
        pixel_format: "mjpeg2rgb" #"yuyv2rgb" #"mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
        av_device_format: "YUV422P"
        image_width: 1280
        image_height: 720
        camera_name: "usb_cam_0"
        camera_info_url: "package://usb_cam/config/camera_info.yaml"
        brightness: -1
        contrast: -1
        saturation: -1
        sharpness: -1
        gain: -1
        auto_white_balance: true
        white_balance: 4000
        autoexposure: true
        exposure: 100
        autofocus: false
        focus: -1

  usb_cam_1:
    usb_cam:
      ros__parameters:
        video_device: "/dev/video2"
        framerate: 5.0
        io_method: "mmap"
        frame_id: "usb_cam_0"
        pixel_format: "mjpeg2rgb" #"yuyv2rgb" #"mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
        av_device_format: "YUV422P"
        image_width: 1280
        image_height: 720
        camera_name: "usb_cam_0"
        camera_info_url: "package://usb_cam/config/camera_info.yaml"
        brightness: -1
        contrast: -1
        saturation: -1
        sharpness: -1
        gain: -1
        auto_white_balance: true
        white_balance: 4000
        autoexposure: true
        exposure: 100
        autofocus: false
        focus: -1